### ISSUE TITLE
Importing addons

### ISSUE THREAD

**Issue by dorp92** [TylerGubala/blenderpy#14]
Hello,
I am trying to import an addon called BlendLuxCore (https://luxcorerender.org/download/)
What I tried:

    import bpy
    import addon_utils
    addon_utils.enable(module_name="BlendLuxCore")

And I am getting:

>Traceback (most recent call last):
  File "C:\Users\dorp\AppData\Local\Continuum\Anaconda3\2.79\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\dorp\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\__init__.py", line 13, in <module>
    from .bin import pyluxcore
ImportError: DLL load failed: The specified module could not be found.

Now the dll is where it should be:
![explorer_2018-09-12_15-18-52](https://user-images.githubusercontent.com/18538356/45424452-434d6100-b69f-11e8-894d-dc745c2a1544.png)
And when I try the same thing from inside blender built in interpreter it works flawlessly:
![image](https://user-images.githubusercontent.com/18538356/45424498-5eb86c00-b69f-11e8-825d-d76bd0340095.png)
What could be the problem and how can I fix it?

**Comment by TylerGubala** [comment]
Interesting! I'm away on travel work and will have to look at this over the weekend.

So you are doing `import bpy import addon_utils`?

I think that's invalid syntax, are you actually doing `from bpy import addon_utils`?

One of the problems here I think is that the Blender python system works very differently than Blender built as a Python module.

That being said, I think your .dll is in the correct place for the Blender addon search method, but I'm not 100% certain that it is in the correct place for the Python .dll path.

I'm going to have to look into this more when I get back from my work trip, but maybe you could try copying the .dll into your `site-packages` directory.

Let me do more reading and investigation; I'm sure something can be done to simplify the process.

Thanks for your patience!

**Comment by dorp92** [comment]
On LuxCore's website it says 2.79b is required,
Your code prints "2.79 (sub 6)"
I am not sure it's the same but it could be. 

`import addon_utils` works fine.
I will test copying the addon to site packages and report results.
Thanks a lot and keep up the good work!

**Comment by dorp92** [comment]
I tried to copy the addon to site-packages and some more tricks, nothing seems to work.
It always fail at `from .bin import pyluxcore`

**Comment by TylerGubala** [comment]
Looking at your image there, you have the LuxCore renderer directory at the Blender application level directory

`C:/Users/dorp/AppData/Roaming/Blender Foundation/Blender/2.79/scripts/addons`

But really shouldn't this be

`{YOUR_VENV_DIR}/Scripts/2.79/addons`?

Trying to eliminate everything that I could debug from here.

**Comment by dorp92** [comment]
I don't think so because blender itself put it there. (After installation from the "user preferences"->"addons" menu)

**Comment by TylerGubala** [comment]
Okay, I will have to look at this over the weekend, then. I'm... not exactly sure what the interplay between the Blender as a Python module and a typical Blender addon would be at the moment. I've been solely focused on getting as many builds available as possible for different python versions.

I'll let you know once I am back at my own machine for testing.

Thanks again!

**Comment by TylerGubala** [comment]
Here's what I did:

    py

>Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

    import bpy

>AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead

    bpy.ops.wm.addon_install(filepath='C:/Users/TGubs/Downloads/BlendLuxCore/BlendLuxCore-v2.0-win64-opencl.zip')

>addon_utils.disable: BlendLuxCore not disabled
Modules Installed (BlendLuxCore) from 'C:/Users/TGubs/Downloads/BlendLuxCore/BlendLuxCore-v2.0-win64-opencl.zip' into 'C:\\Users\\TGubs\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons'
Info: Modules Installed (BlendLuxCore) from 'C:/Users/TGubs/Downloads/BlendLuxCore/BlendLuxCore-v2.0-win64-opencl.zip' into 'C:\\Users\\TGubs\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons'
Info: Modules Installed (BlendLuxCore) from 'C:/Users/TGubs/Downloads/BlendLuxCore/BlendLuxCore-v2.0-win64-opencl.zip' into 'C:\\Users\\TGubs\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons'
{'FINISHED'}

    import addon_utils
    addon_utils.enable(module_name="BlendLuxCore")

>Traceback (most recent call last):
  File "C:\Users\TGubs\Code\Python\blender_test\venv\Scripts\2.79\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\TGubs\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\__init__.py", line 13, in <module>
    from .bin import pyluxcore
ImportError: DLL load failed: The specified module could not be found.

I think this is correct though because here:

https://github.com/LuxCoreRender/BlendLuxCore/issues/138#issuecomment-383510605

They are saying that the version of Python also matters; you need Python 3.5. I'll try to get the other python version builds working soon.

**Comment by dorp92** [comment]
Most of the addons are compiled to python 3.5 because that what blender uses at the moment.
Hence they will not work with blenderpy, I am not sure if there is a good solution.
But I would like to suggest that one of the builds should always be aligned with blenders python version. (3.5 at the moment)

**Comment by dorp92** [comment]
After compiling BlendLuxCore to python 3.6 it worked flawlessly, Thanks!

**Comment by TylerGubala** [comment]
@dorp92 Great! I'll still get those other builds working though.

Thanks for the awesome example case!

**Comment by caniko2** [comment]
Hey, I tried to run `bpy.ops.wm.addon_enable(module="object_print3d_utils")`, but I get:
```
Exception in module unregister(): 'C:\\Users\\Can\\Projects\\CINPLA\\MyoA\\test\\Scripts\\2.79\\scripts\\addons\\object_print3d_utils\\__init__.py'
Traceback (most recent call last):
  File "C:\Users\Can\Projects\CINPLA\MyoA\test\Scripts\2.79\scripts\modules\addon_utils.py", line 313, in enable
    mod.unregister()
  File "C:\Users\Can\Projects\CINPLA\MyoA\test\Scripts\2.79\scripts\addons\object_print3d_utils\__init__.py", 
line 203, in unregister
    bpy.utils.unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

Error: Traceback (most recent call last):
  File "C:\Users\Can\Projects\CINPLA\MyoA\test\Scripts\2.79\scripts\modules\addon_utils.py", line 313, in enable
    mod.unregister()
  File "C:\Users\Can\Projects\CINPLA\MyoA\test\Scripts\2.79\scripts\addons\object_print3d_utils\__init__.py", 
line 203, in unregister
    bpy.utils.unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

Error: Traceback (most recent call last):
  File "C:\Users\Can\Projects\CINPLA\MyoA\test\Scripts\2.79\scripts\modules\addon_utils.py", line 313, in enable
    mod.unregister()
  File "C:\Users\Can\Projects\CINPLA\MyoA\test\Scripts\2.79\scripts\addons\object_print3d_utils\__init__.py", 
line 203, in unregister
    bpy.utils.unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Can\Projects\CINPLA\MyoA\test\Scripts\2.79\scripts\modules\bpy\ops.py", line 189, in __call__    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Can\Projects\CINPLA\MyoA\test\Scripts\2.79\scripts\modules\addon_utils.py", line 313, in enable    mod.unregister()  File "C:\Users\Can\Projects\CINPLA\MyoA\test\Scripts\2.79\scripts\addons\object_print3d_utils\__init__.py", line 203, in unregister
    bpy.utils.unregister_class(cls)RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)
```

**Comment by TylerGubala** [comment]
@caniko2 very strange, I get an altogether different error:

>Microsoft Windows [Version 10.0.18362.239]
>(c) 2019 Microsoft Corporation. All rights reserved.

>C:\Users\TGubs>cd source\repos\blendertest

>C:\Users\TGubs\source\repos\blendertest>"venv\scripts\activate"

>(venv) C:\Users\TGubs\repos\blendertest>py
>Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] on win32
>Type "help", "copyright", "credits" or "license" for more information.
`>>> import bpy`
>AL lib: (EE) UpdateDeviceParams: Failed to set 44000hz, got 48000hz instead
`>>>import addon_utils`
`>>>addon_utils.enable (module_name="object_print3d_utils")`

>[object_print3d_utils]
>3d Print Toolbox: Updating Panel locations has failed

>Error:
>`bpy_prop_collection[key]: key "object_print3d_utils" not found`
><module 'object_print3d_utils' from 'C:\\Users\\TGubs\\source\\repos\\blendertest\\venv\\Scripts\\2.79\\scripts\\addons\\object_print3d_utils\\__init__.py'>

Though

>3d Print Toolbox: Updating Panel locations has failed

Makes me thing this is because the GUI isn't initialized.

**Comment by caniko2** [comment]
Hmm, very probable. This add-on runs in the 3D view pane. I need the volume calculation tool of this add-on. What about my error?

Another idea: Is there a way to get one function from the add-on? Maybe go into the source and grab it? Is there a more streamlined way? What do you think?

**Comment by TylerGubala** [comment]
If you _only_ need the query volume portion, that should be easy enough to import by itself; the add-on initialization in the 3d view is limited to only the `__init__.py` of the package while the volume function is in `operators.py`.

However that doesn't tell the full story; what you actually probably want is the `mesh_helpers.py` function `bm_calc_volume()`.

Here's what I would do (while being blissfully unaware of what your requirement actually is):

```
import bpy
from object_print3d_utils.mesh_helpers import bmesh_copy_from_object

# Create an empty mesh and the object.
mesh = bpy.data.meshes.new('Basic_Cube')
basic_cube = bpy.data.objects.new("Basic_Cube", mesh)

# Construct the bmesh cube and assign it to the blender mesh.
bm = bmesh.new()
bmesh.ops.create_cube(bm, size=1.0)
bm.to_mesh(mesh)
bm.free()

bmesh_copy_from_object(basic_cube).calc_volume()
```

Code for creating the new mesh taken from [here](https://blender.stackexchange.com/questions/63546/create-a-cube-in-blender-from-python?rq=1)

Import your required function, create the object and calculate the volume as necessary.

Some addons are specifically gui based, so your mileage may vary.

**Comment by caniko2** [comment]
Thanks for the help!

I found the same solution as you did while digging through the source of the add-on. We are doing research on muscle cells. Each blender vertex represents a fluorescence protein, confocal microscopy. I need to calculate the geodesic distance, and get some other futures. Almost done :)

**Comment by caniko2** [comment]
Thanks for the help!

I found the same solution as you did while digging through the source of the add-on. We are doing research on muscle cells. Each blender vertex represents a fluorescence protein, confocal microscopy. I need to calculate the geodesic distance, and get some other futures. Almost done :)

**Comment by TylerGubala** [comment]
Sounds cool, admittedly Chinese to me.

Hope your research goes well!

**Comment by TylerGubala** [comment]
Information about importing addons has been added to the documentation, updating the readme with an FAQ now.
