### ISSUE TITLE
ImportError: DLL load failed:

### ISSUE THREAD

**Issue by gerroon** [TylerGubala/blenderpy#15]
HI

I installed it using pip on Windows 10 x64 Python37 . Then I fire ipython, then type "import bpy" this is what I got

: import bpy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-3b0a44bbcc0a> in <module>
----> 1 import bpy

ImportError: DLL load failed: The specified module could not be found

thanks

**Comment by TylerGubala** [comment]
Hi there!

Thanks for filing the issue.

Could I get some more information about the environment that you are using this in? Namely:

- Are you using a `venv`?
- Is this some form of Iron Python? Iron Python is not supported. (you say ipython?)
- Could you please paste the entire stack trace of the crash? That would be very helpful.

Thanks in advance!

**Comment by gerroon** [comment]
Hi

I am not using venv, just installed it systemwide using pip3 install bpy

I am not using Iron Python. Ipython is part fo that Jupyter thing, Py console

Can you tell me how I get the stack trace of the crash on Windows?


thanks

**Comment by gerroon** [comment]
Thanks, let me know if you need testing

**Comment by micmelesse** [comment]
Is there any update one this. I am also using python 3.7 and did a system wide install using `pip3 install bpy`.

**Comment by TylerGubala** [comment]
Unfortunately I've been a bit busy with work lately, I have a fix in the works, but it may take a little while, as I am also chasing down Mac compatibility currently (just bought a used Mac to test).

Thanks for your patience.

**Comment by isaironi** [comment]
Hi, i have the same problem. The python I am using is python 3.4.3 and i did install it using a virtualenv. I also tried installing this a while back using Linux Mint but couldn't seem to get it work either. Is this incompatible with virtual environments?

**Comment by TylerGubala** [comment]
Currently, blenderpy only works for Python versions in the 3.6.x family,
and only for Windows.

I am working on the other builds, but due to work, have a very limited time
to do so.

If you have a PR for a fix for Linux, I would happily merge it.

Let me kniw if you have any questions or further issues.

**Comment by caniko2** [comment]
I get the same issue with 3.6.8

**Comment by TylerGubala** [comment]
@caniko2 Can you let me know what OS, platform (CPython I'm guessing?) Etc so that I can nail this down better? Should work for Windows CPython 3.6.x

**Comment by caniko2** [comment]
Yes, CPython 3.6.x Windows 10

**Comment by caniko2** [comment]
Does Blender support pypy or jpython?

**Comment by TylerGubala** [comment]
Blender might to some level, but this project targets neither of those environements currently.

**Comment by caniko2** [comment]
We are doing physiology research, and need this to work. I have worked hard, and may lose my chance to get credit for an article if this doesn't work. Please fix it ASAP

**Comment by TylerGubala** [comment]
I cannot replicate the issue. Can someone please provide their complete steps to arrive at the issue point? I installed Python 3.6.8 32 and 64 bit on Windows and had 0 problems. I would like to fix this for whoever is having the issue but am struggling to replicate it.

> Microsoft Windows [Version 10.0.18362.207]
> (c) 2019 Microsoft Corporation. All rights reserved.

```
C:\Users\TGubs>cd C:\Users\TGubs\Code\Python\blender_test\venvs

C:\Users\TGubs\Code\Python\blender_test\venvs>py -3.6-32 -m venv 3.6.8-32

C:\Users\TGubs\Code\Python\blender_test\venvs>py -3.6-64 -m venv 3.6.8-64

C:\Users\TGubs\Code\Python\blender_test\venvs>"3.6.8-32/Scripts/activate"

(3.6.8-32) C:\Users\TGubs\Code\Python\blender_test\venvs>py -m pip install --upgrade pip
```

> Collecting pip
>   Using cached https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl
> Installing collected packages: pip
>   Found existing installation: pip 18.1
>     Uninstalling pip-18.1:
>       Successfully uninstalled pip-18.1
> Successfully installed pip-19.1.1

`(3.6.8-32) C:\Users\TGubs\Code\Python\blender_test\venvs>py -m pip install bpy`

> Collecting bpy
>   Using cached https://files.pythonhosted.org/packages/98/cb/d449719f69e225f76aa3201b2f0f0f04cda5cc6b23753054f2d11c3e2896/bpy-1.2.3-cp36-cp36m-win32.whl
> Installing collected packages: bpy
> Successfully installed bpy-1.2.3

`(3.6.8-32) C:\Users\TGubs\Code\Python\blender_test\venvs>py`

> Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] on win32
> Type "help", "copyright", "credits" or "license" for more information.

`>>> import bpy`

> AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead

`>>> quit()`

> Error: Not freed memory blocks: 8, total unfreed memory 0.004288 MB

```
(3.6.8-32) C:\Users\TGubs\Code\Python\blender_test\venvs>deactivate
C:\Users\TGubs\Code\Python\blender_test\venvs>"3.6.8-64/Scripts/activate"

(3.6.8-64) C:\Users\TGubs\Code\Python\blender_test\venvs>py -m pip install --upgrade pip
```

> Collecting pip
>   Using cached https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl
> Installing collected packages: pip
>   Found existing installation: pip 18.1
>     Uninstalling pip-18.1:
>       Successfully uninstalled pip-18.1
> Successfully installed pip-19.1.1

`(3.6.8-64) C:\Users\TGubs\Code\Python\blender_test\venvs>py -m pip install bpy`

> Collecting bpy
>   Using cached https://files.pythonhosted.org/packages/a1/ca/33d3cb564180e156607ce1c4126b78c6aea23e1d6120de980b113c8c0e9b/bpy-1.2.3-cp36-cp36m-win_amd64.whl
> Installing collected packages: bpy
> Successfully installed bpy-1.2.3
> 

`(3.6.8-64) C:\Users\TGubs\Code\Python\blender_test\venvs>py`

> Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.

`>>> import bpy`

> AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead

`>>> quit()`

> Error: Not freed memory blocks: 8, total unfreed memory 0.008392 MB

`(3.6.8-64) C:\Users\TGubs\Code\Python\blender_test\venvs>`

**Comment by MaikuMori** [comment]
`3.6` worked for me, but we ran into issues where renders didn't match between running the same script via `blender -b -y -P ...` and using blender as python module, so we switched back to running via `blender` as that had correct renders.

**Comment by ashishgopal1414** [comment]
doesn't work for python 3.7.3 also :-(

**Comment by liwenssss** [comment]
is there any solution for python3.7.3?

**Comment by TylerGubala** [comment]
@liwenssss Try the sdist at test.pypi.org:

```
pip install --index-url https://test.pypi.org/simple/
```

Note: depending on your network connection it can take multiple hours to build from sdist.

**Comment by TylerGubala** [comment]
You should be able to `pip install bpy && bpy_post_install` on all platforms but linux now.

Python 3.7.x should work for all but Linux using bpy 2.82

**Comment by avishek-mondal** [comment]
Hi, when I ran  
``` 
pip install bpy && bpy_post_install
```
I get the following error messages - 

```
raceback (most recent call last):
  File "/usr/local/bin/bpy_post_install", line 11, in <module>
    sys.exit(post_install())
  File "/usr/local/lib/python3.7/site-packages/blenderpy/post_install.py", line 47, in post_install
    install_scripts_directory()
  File "/usr/local/lib/python3.7/site-packages/blenderpy/post_install.py", line 43, in install_scripts_directory
    +blender_scripts_search_root_dir)
blenderpy.BlenderScriptsDirUnknownError: Could not find Blender scripts directory in /usr/local/opt
```
Any idea how to solve this?

**Comment by TylerGubala** [comment]
@avishek-mondal let's continue this discussion in #41
