### ISSUE TITLE
Can we convert the .obj file to .jpg ?

### ISSUE THREAD

**Issue by vdsprakash** [TylerGubala/blenderpy#17]
We wants to convert .obj to .jpg, with adding certain rotation. Can you please help this out for us .

**Comment by TylerGubala** [comment]
Hi, 

What you are going to be able to do is going to be somewhat limited by the version of Python that you are constrained to. You can currently use my repository with Python 3.6, I believe, but on other Pythons the DLL is incompatible. 

I just recently started having enough time after work that I can start investigating this a little bit here and there, but until I get the other builds working, you may be able to do something like the following (depending on what "certain rotation" is) on Python 3.6:

From a shell environment, or (Visual Studio Code terminal, which I highly recommend)
```
py -3.6-64 -m venv venv
venv/Scripts/activate
(venv) py -m pip install --upgrade pip
(venv) py -m pip install appdirs bpy
```

```
#! /usr/bin/python
# -*- coding: UTF-8 -*-
"""
Output jpg from obj file
"""
# STD_LIB imports
import os

# PYPI imports
from appdirs import AppDirs
import bpy

# Please replace with what is relevant to your use case
APP_NAME = "MyApp"
APP_AUTHOR = "YourName"
APP_STORAGE = AppDirs(APP_NAME, APP_AUTHOR)

FILE_LOCATION = os.path.join(APP_STORAGE.user_data_dir, "filename.obj")
RENDER_LOCATION = os.path.join(APP_STORAGE.user_data_dir, "filename.jpg")

# Import the desired .obj file, using the full path to the file.
bpy.ops.import_scene.obj(filepath=FILE_LOCATION)

# Get the imported object from the context
imported_object = bpy.context.selected_objects[0]

# Apply rotation in radians
CERTAIN_ROTATION = (0, 0, 0.261799)
imported_object.rotation_euler = CERTAIN_ROTATION

# save the rendered images
bpy.data.scenes['Scene'].render.filepath = RENDER_LOCATION
bpy.ops.render.render( write_still=True )
```

See the following sources, used for the example:

[Importing Objects through scripting](https://blender.stackexchange.com/questions/72928/blender-2-78-obj-import-via-script)
[Rotating objects via script](https://blender.stackexchange.com/questions/43086/how-to-rotate-an-object-in-blender-2-74-using-python-script)
[Scripting and Rendering](https://stackoverflow.com/questions/14982836/rendering-and-saving-images-through-blender-python)

Please let me know if you have nay further issues. Thanks!

**Comment by vdsprakash** [comment]
Thank you for your response. Will executing, I am getting this issue , once can you check out this.

Saved: 'C:\Users\Denny\AppData\Local\YourName\MyApp\filename.png'
 Time: 00:00.35 (Saving: 00:00.07)

Exception ignored in: <bound method CyclesRender.__del__ of <bpy_struct, Struct("CYCLES")>>
Traceback (most recent call last):
  File "C:\Users\Zebi\Anaconda3\envs\first__env\2.79\scripts\addons\cycles\__init__.py", line 66, in __del__
TypeError: 'NoneType' object is not callable
Error: Not freed memory blocks: 8, total unfreed memory 0.008392 MB
![filename](https://user-images.githubusercontent.com/23026717/57287912-1b02ee80-70d6-11e9-80b9-bb80a972d5c3.png)


This is the output.png that i am getting.

**Comment by TylerGubala** [comment]
Please provide me with your expected output, what you think you should be getting.

It looks like the image you show in your comment is one of the "Default Cubes" that come in a new Blender scene. You may have to delete that prior to importing your `.obj` file.

At the very least you are getting an image, maybe it's not the one you want, but it's _something_.

I would recommend trying the script you modified to produce the above result in Blender's built in interpriter, and heading over to the Blender Stack Exchange to speak with others who are doing somethong similar.

It will always be more straightforward for you to impliment what you are trying to do in the Blender environment first, then migrate your code for use as a script with the `bpy` module.

Please either reproduce this in Blender, and show me the output you want, or give me something more to work with, such as more information. I think you may just need to modify the example script to get it to do what you want, as it was only a very general example, and I'm not sure what _exactly_ you're trying to accomplish.

**Comment by TylerGubala** [comment]
If I am not provided with new information I am going to assume this issue is closed.

**Comment by ldlasso2** [comment]
> Thank you for your response. Will executing, I am getting this issue , once can you check out this.
> 
> > Saved: 'C:\Users\Denny\AppData\Local\YourName\MyApp\filename.png'
> > Time: 00:00.35 (Saving: 00:00.07)
> > Exception ignored in: <bound method CyclesRender.**del** of <bpy_struct, Struct("CYCLES")>>
> > Traceback (most recent call last):
> > File "C:\Users\Zebi\Anaconda3\envs\first__env\2.79\scripts\addons\cycles__init__.py", line 66, in **del**
> > TypeError: 'NoneType' object is not callable
> > Error: Not freed memory blocks: 8, total unfreed memory 0.008392 MB
> 
> This is the output.png that i am getting:
> 
> ![filename](https://user-images.githubusercontent.com/23026717/57287912-1b02ee80-70d6-11e9-80b9-bb80a972d5c3.png)

The cube is default, you have to eraser, I put this code below the line _**"imported_object = bpy.context.selected_objects[0]"**_  and it worked
scene = bpy.context.scene

for ob in scene.objects:
    if ob.type == 'MESH' and ob.name.startswith("Cube"):
        ob.select = True
    else: 
        ob.select = False

bpy.ops.object.delete()

**Comment by Roshni-Jhariya** [comment]
Hi can you help me with a python code that converts .obj file to slices that is many png files?
