### ISSUE TITLE
Error with installing.

### ISSUE THREAD

**Issue by vdsprakash** [TylerGubala/blenderpy#18]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5k1z9eff/bpy/

with command **pip install bpy**

**Comment by TylerGubala** [comment]
Please provide your environment/ Python configuration.

**Comment by vdsprakash** [comment]
As this package supports only for Windows alone. I got an error. I am using Ubuntu 18.04.

**Comment by TylerGubala** [comment]
Same as #1
