### ISSUE TITLE
Render inconsistency

### ISSUE THREAD

**Issue by TylerGubala** [TylerGubala/blenderpy#19]
`3.6` worked for me, but we ran into issues where renders didn't match between running the same script via `blender -b -y -P ...` and using blender as python module, so we switched back to running via `blender` as that had correct renders.

_Originally posted by @MaikuMori in https://github.com/TylerGubala/blenderpy/issues/15#issuecomment-510317203_

**Comment by TylerGubala** [comment]
@MaikuMori if you can post your issue, the expected output vs the real output as well as source data, then I might be able to see what the problem is. Without that, I may have to close the new issue.

**Comment by MaikuMori** [comment]
I'll see if I can make smaller example. 

Basically the output from `bpy` was different as if the spec roughness on material node was lower.

![example](https://user-images.githubusercontent.com/28470/61167143-e3e90780-a574-11e9-829d-86fda12a1207.png)

Maybe I can provide the assets or the material privately, I'll verify that.

**Comment by TylerGubala** [comment]
@MaikuMori you aren't by chance using the 2.8 preview EEVEE renderer for your `blender` example, are you?

**Comment by MaikuMori** [comment]
No, it's the same version. We might move to 2.8 in the future, but for now it's 2.79.

**Comment by TylerGubala** [comment]
If you aren't able to provide any further insight, or test data in a week I'll be temporarily closing the issue as `wontfix` because I'm not sure what the issue _is_.

My thought was internal engine vs Cycles vs EEVEE but if you are saying that you're using the same renderer in whatever code you made (could I have the code please?) then I am really unsure what could be causing the difference.

It's not even like it's a subtle difference either... it would really be apprciated if you could lend me your code and sample data!

**Comment by TylerGubala** [comment]
Will not fix until reproducable data is provided
