### ISSUE TITLE
Blender 2.8 support

### ISSUE THREAD

**Issue by beardedhog** [TylerGubala/blenderpy#25]
Now, as Blender 2.8 was recently released, it might be a good time to add Python 3.7/Blender 2.8 support.

There has been added a convenient `bpy` make target to compile Blender as a Python module, but the compilation process is still somewhat tricky.

**Comment by jingle1000** [comment]
Any update on this?

**Comment by TylerGubala** [comment]
Nope, not yet. My first priority is Mac support, I just got the Mac I
recently purchased up and running in order to start supporting additional
OS.

Thanks for your patience.

**Comment by mklemarczyk** [comment]
Hello, I would like to contribute to make it working with Blender 2.80

**Comment by TylerGubala** [comment]
Okay; currently development for aupporting other Python versions is ongoing
in the bpy-make repo

**Comment by TylerGubala** [comment]
A fix for this is pending an upgrade to the pypi file size limit for this project. [Related](https://github.com/pypa/pypi-support/issues/362)
