### ISSUE TITLE
document usage with pyinstaller

### ISSUE THREAD

**Issue by TylerGubala** [TylerGubala/blenderpy#28]
I am having the problem documented in #13 but mine is related to PyInstaller. I am using python 3.6.6 on Windows 10 along with bpy1.2.4a0. 

The packaging of my program is successful but then you get the "'bpy_types' module" since as you said the python executable is not alongside 2.79.
The crude solution of copying 2.79 folder cant work for me as my program's executable created by PyInstaller using the --onefile option which decompresses its contents to the temporary _MEIXXXX directory.
is there a workaround for this?

_Originally posted by @kostasmarkakis in https://github.com/TylerGubala/blenderpy/issues/13#issuecomment-550291058_

**Comment by TylerGubala** [comment]
@kostasmarkakis You need to define the 2.79 directory as "data" using the `--add-data` construct in `PyInstaller`. Documentation [here](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-data-files)

I was able verify that this works by producing a small test environment for myself. I actually just used a file I had from solving someone else's issue...

Anyways, I had a small file, and I use virtual environments produced by `venv`. The following should work for you.

**In the terminal**:

```batch
mkdir test_bpy_pyinstaller
cd test_bpy_pyinstaller

py -3.6-64 -m venv venv
venv\Scripts\activate
py -m pip install bpy
py -m pip install pyinstaller
```

**In a new Python file in your `test_bpy_pyinstaller` folder**, called `test.py`:

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
try:
    import bpy
except:
    print("Failed to import bpy")
else:
    print("Successfully imported bpy!")
```

**Back in the terminal**:

```batch
pyinstaller --add-data="venv/Scripts/2.79;2.79" test.py

[  PyInstaller does its thing...  ]

dist\test\test

[  Should see "Successfully imported bpy!"  ]
```

Please try it out and let me know if it works or not. It worked for me, so I'll close this and you can open it with any new errors.

If you have further errors for some reason, please post the full details, because packaging with `PyInstaller` can be quite complex at times.

Thanks for the issue!

**Comment by ideasman42** [comment]
Note that the:  `pyinstaller foo.py  --collect-data bpy` can be used with recent builds.
