### ISSUE TITLE
[Error] python setup.py

### ISSUE THREAD

**Issue by mgautam98** [TylerGubala/blenderpy#39]
**Describe the bug**
Not able to install bpy. Throws the following error
```
(test) mgautam@DESKTOP-4D7S2UN:~/projects/blender$ pip install bpy && bpy_post_install
Collecting bpy
  Using cached https://files.pythonhosted.org/packages/bc/e2/20c6d56f1143e13c0fc24a7d987ee28e4949b8edbbbb1b66f705d129bdc5/bpy-0.0.0a0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/mgautam/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ta6tz58_/bpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ta6tz58_/bpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-ta6tz58_/bpy/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "/home/mgautam/anaconda3/lib/python3.7/tokenize.py", line 397, in find_cookie
        codec = lookup(encoding)
    LookupError: unknown encoding: future_fstrings
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/mgautam/anaconda3/lib/python3.7/tokenize.py", line 449, in open
        encoding, lines = detect_encoding(buffer.readline)
      File "/home/mgautam/anaconda3/lib/python3.7/tokenize.py", line 436, in detect_encoding
        encoding = find_cookie(second)
      File "/home/mgautam/anaconda3/lib/python3.7/tokenize.py", line 405, in find_cookie
        raise SyntaxError(msg)
    SyntaxError: unknown encoding for '/tmp/pip-install-ta6tz58_/bpy/setup.py': future_fstrings
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by TylerGubala** [comment]
Hello @mgautam98 ,

The error you are receiving here is unfortunately symptomatic of me not having the [required space to host my package on pypi](https://github.com/pypa/pypi-support/issues/362), which means that you cannot install the `.whl` code package, which is normally easier.

Instead, until the time comes when I get the upload limit increase for my package on pypi, you must either install from the `.whl` files [here](https://drive.google.com/drive/folders/18HFAbqoPBF6ItYrwbeQB-xSEbq3VudsI?usp=sharing) by performing the following command:

```bash
pip install bpy-2.82-cp37-cp37m-linux_x86_64.whl && bpy_post_install
```

Alternatively you can install all [the prerequisites](https://github.com/TylerGubala/blenderpy/wiki#prerequisites-1) and then continue using `pip install bpy && bpy_post_install`, which will create a custom build from sources.

Please note that building from sources takes on average two hours. I _strongly_ recommend installing from the `.whl`  file.

**Comment by TylerGubala** [comment]
Since there has not been any action on this issue, I am closing it. If you continue to have difficulty using this repo, please submit a new issue with further details.
