### ISSUE TITLE
Offline installation 

### ISSUE THREAD

**Issue by Zigler** [TylerGubala/blenderpy#44]
**Problem**
If I wanted to install this on a computer that is isolated from the internet I do not see an easy way to do so as it relies on active git and svn repos.

**Potential Solution**
The ability to install bpy offline independent of internet usage.

**Alternatives**
Calling Python Binaries to accomplish tasks without api support.

**Comment by TylerGubala** [comment]
Sorry but what is  your expectation on how this  would work in practice?

How are you installing other python packages in an offline situation?

Would downloading the wheels from [google drive](https://drive.google.com/drive/folders/1uSiTQLvlUxu7PDT2TCT4XIrwGwn1WWph?usp=sharing) onto a usb stick and installing from `wheel` offline suffice?

I'm just not sure what your *exact* intended use case is. As there is certainly more to an offline installation solution other than "it has to work offline".

In what environment? Would you have the `wheel` library preloaded on your python?

**Comment by Zigler** [comment]
> Sorry but what is your expectation on how this would work in practice?

Apologizes for not being clearer, but the machines are isolated from the network.

> How are you installing other python packages in an offline situation?

USB transferred offline wheel's are utilized along with the dependencies and pip installing the wheel's are the typical solution. Occasionally building from source files during the install by utilizing MSVC, Clang, CMake, MinGW, and/or MSBuild.

> Would downloading the wheels from [google drive](https://drive.google.com/drive/folders/1uSiTQLvlUxu7PDT2TCT4XIrwGwn1WWph?usp=sharing) onto a usb stick and installing from `wheel` offline suffice?

Yes it would assuming it doesn't do a repo check upon running like the *pip install* did. I was curious why these weren't posted on the [PyPi](https://pypi.org/project/bpy/#files) .

> I'm just not sure what your _exact_ intended use case is. As there is certainly more to an offline installation solution other than "it has to work offline".

I would like to install the module to use with any current version of blender. This way if I happen to use an outdated version of blender due to installation timelines then the module still works.

> In what environment? Would you have the `wheel` library preloaded on your python?

win_amd64 ,Python 3.7, and would be completely isolated from network connection. Git and SVN would be installed, but access to outside repos would not be possible.

This should give you a better idea of what type of installation is attempted to be accomplished. 

Finally a request based upon offline installation, please document the requirement to have SVN and Git both installed and display a dependency specific error for which one is not installed or make installation independent and base dependencies on a mirror. 

These may already be features that are available but that wasn't intuitive through reading the documentation. In fact, I didn't know I needed SVN until I dug around the closed issues.

**Comment by TylerGubala** [comment]
> This should give you a better idea of what type of installation is attempted to be accomplished.

Actually it really doesn't, unfortunately. 

I think you would be better suited to cloning the `git` and `svn` repos for  whatever version of Blender you desire onto a usb stick and distributing builds you make yourself if the `wheels` I provided aren't working for you, especially if you are working offline. That will get you familiar with the build system that Blender has and allow you to apply fixes on-site. If you run into errors, there is a vast network of support for self building at [Blender Devtalk](https://devtalk.blender.org/).

> Finally a request based upon offline installation, please document the requirement to have SVN and Git both installed

This is already documented [here](https://github.com/TylerGubala/blenderpy/wiki#prerequisites-1)

**Comment by TylerGubala** [comment]
Hi!

There  was additionally a hotfix for `bpy` that released with `2.82.1` fixing the `bpy_post_install` script. I neglected to upload the `2.82.1` `wheel` to pypi. 

So sorry about any confusion that may have caused; it is up now.

Thanks.
