### ISSUE TITLE
Adopt PEP 517 to manage build-time dependencies

### ISSUE THREAD

**Issue by uranusjr** [TylerGubala/blenderpy#47]
**Is your feature request related to a problem? Please describe.**
Currently, bpy cannot be built without future-fstring being installed manually first, since the `setup.py` file is itself using the `future-fstring` encoding, and cannot be parsed to get the values in `setup_requires`. It makes the build fail with a cryptic message

```
SyntaxError: unknown encoding for setup.py: future_fstring
```

**Describe the solution you'd like**
Python packaging offers [PEP 517](https://www.python.org/dev/peps/pep-0517/) as a way to tell pip about dependencies needed to be installed *before* the setup script is run. This is done by adding a `pyproject.toml` file and listing the packages needed:

```toml
[build-system]
requires = ["future-fstring", "setuptools", "wheel"]
build-backend = "setuptools.build_meta"
```

**Describe alternatives you've considered**
I guess it’s an option to not use the `future_fstring` encoding in setup.py instead 🙂 Or not publishing the `.tar.gz` bundle at all.

**Additional context**
Also see: [What the heck is pyproject.toml?](https://snarky.ca/what-the-heck-is-pyproject-toml/), which is a better write-up on what to do and why. The PEP can be difficult to digest.

**Comment by TylerGubala** [comment]
This is a great point; I was not even aware of PEP517 honestly. I was searching for a way to do this exact step but was having trouble finding if it was in any of the other, more surface-visible metadata files. 

Thanks for the great write up, I will start looking at this right away!

**Comment by TylerGubala** [comment]
I believe this is resolved as of https://github.com/TylerGubala/blenderpy/commit/1155daf76373dace5dd5f23bd36286100469af00

Please let me know if there are any other improvements to be had!
