### ISSUE TITLE
bpy.ops.render.render breaks code without exception

### ISSUE THREAD

**Issue by Joetib** [TylerGubala/blenderpy#51]
I am writing a script that unwraps an image around a blender model and renders it to png.
My script works fine, when I run with blender in background mode

But when I run it with `bpy` (this project), all of my code runs until it gets to `bpy.ops.render.render(write_still=True)` then, the code breaks without even raising an exception. This even stops my running flask server.

**To Reproduce**
```python
def obj_material_texture_UVunwrap(objname, filename):
    """
    Handles unwrapping an object, given the object name and the name
    of the image file.
    """
    path = os.path.join(TextureFolder, filename)
    materials = bpy.data.materials
    material = materials.get("mat")
    if not material:
        material = materials.new("mat")
    material.use_nodes = True
    if material.node_tree:
        material.node_tree.links.clear()
        material.node_tree.nodes.clear()
    nodes = material.node_tree.nodes
    links = material.node_tree.links
    output = nodes.new(type="ShaderNodeOutputMaterial")
    diffuse = nodes.new(type="ShaderNodeBsdfDiffuse")
    imgTex = bpy.data.images.load(path)
    node_texture = nodes.new(type="ShaderNodeTexImage")
    node_texture.image = imgTex
    node_texture.location = 0, 200
    tex_coord = nodes.new(type="ShaderNodeTexCoord")  # NEW
    links = material.node_tree.links
    link = links.new(tex_coord.outputs["UV"], node_texture.inputs["Vector"])  # NEW
    link = links.new(node_texture.outputs[0], nodes.get("Diffuse BSDF").inputs[0])
    link = links.new(diffuse.outputs["BSDF"], output.inputs["Surface"])
    obj = bpy.data.objects[objname]
    obj.active_material = material
    bpy.ops.object.select_all(action="DESELECT")
    bpy.data.objects[objname].select_set(True)
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.select_all(action="SELECT")
    bpy.ops.uv.smart_project()
    bpy.ops.object.mode_set(mode="OBJECT")
    render_location = "c:\\blenderOutput\\renderedimage.png"
    print(f"Rendering to {render_location}")
    bpy.context.scene.render.filepath = render_location
    bpy.ops.render.render(write_still=True)
    print(f"Completed: Rendering to {render_location}")

```
error happens on 
```
bpy.ops.render.render(write_still=True)
```
I am on Windows 10 x64 version 2004
Also python 3.7.7

**Expected behavior**
Expected to see the file rendered and 
the print message `completed: Rendering to c:\\blenderOutput\\renderedimage.png`
 
**Desktop (please complete the following information):**
 - OS: Windows 10 x64 version 2004

**Comment by TylerGubala** [comment]
You were able to use flask while in Blender script execution mode? That is
a very unique setup to me.

Have you seen this?

https://blenderartists.org/t/crashing-blender-using-bpy-ops-render-render-from-a-different-thread/536849/2

Flask usually has threading to handle requests efficiently to my knowledge.
I really doubt that you'd be able to use Blender in the same place you are
using flask, you will probably have to come up with some custom hander to
send the signal to render into the separate dedicated Blender process and
exchange the rendered image somehow.

How did you have this working previously? I will look at your example code
later but I get the feeling I will not be able to reproduce it if this is a
threading issue.

**Comment by Joetib** [comment]
Well taking the flask part out and running the script still breaks at the same point. However the script works fine when run with `blender.exe` in background mode

**Comment by TylerGubala** [comment]
Where is "TextureFolder" defined?

This example needs to be complete before it can be reproducible.

```
(venv) PS C:\Users\TGubs\Code\Python\blenderpy-test> py test.py
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    obj_material_texture_UVunwrap("Cube", r"C:\Temp\image.jpg")
  File "test.py", line 10, in obj_material_texture_UVunwrap
    path = os.path.join(TextureFolder, filename)
NameError: name 'TextureFolder' is not defined
Error: Not freed memory blocks: 8, total unfreed memory 0.010223 MB
```

**Comment by TylerGubala** [comment]
Maybe try setting your rendering engine first?

This works:

```python
import bpy
import bmesh
import mathutils

mesh = bpy.data.meshes.new('cube')
ob = bpy.data.objects.new('cube', mesh)

bpy.context.collection.objects.link(ob)

bm = bmesh.new()
bmesh.ops.create_cube(bm, size=1.0)
bm.to_mesh(mesh)
bm.free()

light_data = bpy.data.lights.new('light', type='POINT')
light = bpy.data.objects.new('light', light_data)
bpy.context.collection.objects.link(light)
light.location = mathutils.Vector((3, -4.2, 5))

cam_data = bpy.data.cameras.new('camera')
cam = bpy.data.objects.new('camera', cam_data)
bpy.context.collection.objects.link(cam)
bpy.context.scene.camera = cam

cam.location = mathutils.Vector((6, -3, 5))
cam.rotation_euler = mathutils.Euler((0.9, 0.0, 1.1))

render_location = r"C:\tmp\image.jpg"
print(f"Rendering to {render_location}")
bpy.context.scene.render.image_settings.file_format = 'PNG'
bpy.context.scene.render.filepath = render_location
bpy.context.scene.render.engine = 'CYCLES'
bpy.ops.render.render(write_still=True)
print(f"Completed: Rendering to {render_location}")
```

![image](https://user-images.githubusercontent.com/22432839/94193316-34007100-fe7e-11ea-8971-901569fd6b72.png)

**Comment by TylerGubala** [comment]
Not a problem! Glad I could help! Feel free to post here anytime, or to
visit Blender Dev talk with any API related questions!

**Comment by Derry-Xing** [comment]
> 

May I ask what script you used？
