### ISSUE TITLE
bpy.ops.render.render() with BLENDER_EEVEE stops the program without raising Exceptions

### ISSUE THREAD

**Issue by darkimage** [TylerGubala/blenderpy#54]
**Describe the bug**
`bpy.ops.render.render` quit execution when rendering with `bpy.data.scenes["Scene"].render.engine = 'BLENDER_EEVEE'`

**To Reproduce**
Running this script in a blender executable works in blenderpy do not:
```python
import bpy
from pathlib import Path

if __name__ == "__main__":
    #This two lines are removed when testing in an actual blender executable
    path = str(Path("./projects/render.blend").absolute()) 
    bpy.ops.wm.open_mainfile(filepath=path)

    renderPath = "H:\\Program Files\\Quixel\\bridge-preview\\src\\render\\render" #using absolute just for testing

    bpy.data.scenes["Scene"].render.filepath = renderPath
    bpy.data.scenes["Scene"].render.engine = 'BLENDER_EEVEE' #CYCLES works

    bpy.ops.render.render(write_still=True)
    print("Render Done") # this line is never reached
```

**Expected behavior**
Blender should render a still frame image to designated path but instead simply quit the program without exceptions  (I don't know if there are limitation in using blender as a python module), cycles works, eevee do not render. 

**Desktop:**
 - OS: Windows
 - Version: bpy-cuda 2.82

**Comment by TylerGubala** [comment]
Hi,

I don't think that EEVEE is available in the Python module.

See also https://devtalk.blender.org/t/python-crashes-when-rendering-with-workbench-or-eevee/8214

**Comment by darkimage** [comment]
Hi and Thank you for the reply,
that was my other solution but having to relay only on bpy would be a better choice but since it's not supported I'll go with this solution, thank you again.
Do you know where I can retrieve a list of what's available in the python module?

**Comment by TylerGubala** [comment]
I don't think that list currently exists. You could always go to the [Blender Developer](https://devtalk.blender.org/) forum and ask around.

For now, it's recommended to try and use Blender from the command line.

**Comment by yaserOSource** [comment]
> **Describe the bug**
> `bpy.ops.render.render` quit execution when rendering with `bpy.data.scenes["Scene"].render.engine = 'BLENDER_EEVEE'`
> 
> **To Reproduce**
> Running this script in a blender executable works in blenderpy do not:
> 
> ```python
> import bpy
> from pathlib import Path
> 
> if __name__ == "__main__":
>     #This two lines are removed when testing in an actual blender executable
>     path = str(Path("./projects/render.blend").absolute()) 
>     bpy.ops.wm.open_mainfile(filepath=path)
> 
>     renderPath = "H:\\Program Files\\Quixel\\bridge-preview\\src\\render\\render" #using absolute just for testing
> 
>     bpy.data.scenes["Scene"].render.filepath = renderPath
>     bpy.data.scenes["Scene"].render.engine = 'BLENDER_EEVEE' #CYCLES works
> 
>     bpy.ops.render.render(write_still=True)
>     print("Render Done") # this line is never reached
> ```
> 
> **Expected behavior**
> Blender should render a still frame image to designated path but instead simply quit the program without exceptions (I don't know if there are limitation in using blender as a python module), cycles works, eevee do not render.
> 
> **Desktop:**
> 
> * OS: Windows
> * Version: bpy-cuda 2.82

I was struggling really badly with this issue. I suspected EEVEE but never got round to switching it. Once I did, everything worked fine. Thanks for posting this....
