### ISSUE TITLE
Trying to install bpy on ubuntu 18.04

### ISSUE THREAD

**Issue by rezhv** [TylerGubala/blenderpy#61]
Is there a way to do that? Considering I install anaconda and use python 3.7 on google co-lab how can I build and install bpy. Are there any instruction I can follow?

**Comment by TylerGubala** [comment]
Hi, thank you for your interest.

**For installing to Ubuntu**:

1. Download the prerequisites for Ubuntu, [as documented on the README.md under "Prerequisites"](https://github.com/TylerGubala/blenderpy#prerequisites)
2. Download the `*.whl` file from the [Releases page](https://github.com/TylerGubala/blenderpy/releases), as [documented on the README.md under "Installing"](https://github.com/TylerGubala/blenderpy#installing)
3. Install the `wheel` file as [documented on README.md under "Installing"](https://github.com/TylerGubala/blenderpy#installing) - Note that you may need to update `pip` and install `wheel`, depending on the type of environment you are using. Documenting every possible use case is not the goal of this repo. If you have issues at this step, then please submit a new issue with the error you encounter, and I will be glad to help.

**For installation to Google Collaboratory**

1. [Install `jupyterlab`](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html) into the `venv` that you installed `bpy` into
2. [Run `jupyter lab`](https://jupyterlab.readthedocs.io/en/stable/getting_started/starting.html)
3. Connect your Google Collaboratory to the Local Jupyter Lab instance you are running
4. If you have further issues or instructions you want to add, then just let me know. FYI, I do not use Google Collaboratory.

If you have further issues, don't hesitate to reach out.
