### ISSUE TITLE
bpy.ops.render.render() causes the program to exit immediately without errors

### ISSUE THREAD

**Issue by dph121** [TylerGubala/blenderpy#66]
When running the most basic code:
_import bpy
bpy.ops.render.render(write_still=True)_
or any code that involves the bpy.ops.render.render() function, no images are produced and the program exits immediately without casting errors, on my computer.

Expected behavior: A file called ".png" created in C:/tmp containing the image of a cube.

I have Python 3.7.6 installed through Anaconda3 (anaconda navigator v1.9.12) on Windows 10. I installed bpy by entering _pip install bpy && bpy_post_install_ in the Anaconda prompt.
I also have the regular version of Blender installed and can generate images by entering the same code in the blender python console.

When entering the code in python running in the anaconda prompt, the process exits immediately without producing an image.
When entering the code in Microsoft Visual Studio 2019, the python console exits without producing an image, and Microsoft Visual Studio generates an error "Could not convert to integer: 3221225477. Path 'exitCode'. Value was either too large or too small for an Int32."
When entering the code in Jupyter Notebook, the kernel dies.

I am new to using bpy, so I may have made stupid mistakes. Other code snippets seem to work fine:
_import bpy
print(list(bpy.context.scene.objects))_
lists the cube, camera, and light as normal.

This resembles issue #54 except that it does not rely on the use of EEVEE.

**Comment by TylerGubala** [comment]
This reminds me most of #51.

Try the solution described there and let me know how it goes.

https://github.com/TylerGubala/blenderpy/issues/51#issuecomment-698555638

**Comment by dph121** [comment]
Somehow I missed that one. Thanks for the quick response, that works!
