### ISSUE TITLE
Render not working

### ISSUE THREAD

**Issue by omararturo** [TylerGubala/blenderpy#69]
Hello Tyler, Good Job!

I have an problem running this basic code in python. This Doesn't throw errors and no save images. 

I guess that an error occurred in Blender, but I can't see it

```
import bpy

bpy.context.scene.render.image_settings.file_format='JPEG'
bpy.context.scene.render.filepath = "D:/test.jpg"
bpy.ops.render.render(write_still=True)
```

**Comment by Derry-Xing** [comment]
Same issue with me


Process finished with exit code -1073741819 (0xC0000005)
