### ISSUE TITLE
Wrong line at the wiki for using prebuild bpy

### ISSUE THREAD

**Issue by dwintergruen** [TylerGubala/blenderpy#70]
Option three how to build with prebuild should be:

 pip install .  --global-option="build_ext" --global-option="--bpy-prebuilt=/Users/dwinter/Documents/Projekte/Blender/blenderpy/blender/macos_bpy/bin" -v

**Comment by TylerGubala** [comment]
That would only be the case for you. People my have built Blender in a different directory from what you are showing there.

Closing as invalid.
