### ISSUE TITLE
How to install bpy in PyCharm IDE?

### ISSUE THREAD

**Issue by JunxuanBai** [TylerGubala/blenderpy#71]
Hello, I wish to install bpy in PyCharm IDE, but I cannot install it correctly. 

After I install **future_fstring**, the IDE can start to install bpy, but it always shows "Installing package 'bpy', ..., Using cached https://...". Also, I tried to use pip to install the bpy package, but it also get stuck at "Using cached bpy-0.0.0a0.tar.gz". 

What should I do to continue the installation?

Thank you!

**Comment by caniko** [comment]
That is strange, I have no issue installing bpy, and I use PyCharm. I believe that your problem is outside of PyCharm, your cached bpy also looks strange "0.0.0a0"?

**Comment by JunxuanBai** [comment]
Thanks for your reply! The problem is the Python version. I found that I can install bpy in Python 3.7.

**Comment by TylerGubala** [comment]
Per the latest comment, I am closing the issue.

If you need further assistance, please open another issue. Thank you!

**Comment by karinoon** [comment]
I have the same issue. At first I was using python 3.8 and later changed to 3.7 but it still didn't work
