### ISSUE TITLE
Error : "marked ‘override’, but does not override" when Building CXX object intern/cycles/render/CMakeFiles/cycles_render.dir/osl.cpp.o

### ISSUE THREAD

**Issue by theottm** [TylerGubala/blenderpy#75]
I get this error during the build when running `pip install -b /media/teddd/IHD/tmp/ bpy`

>[ 22%] Building CXX object intern/cycles/render/CMakeFiles/cycles_render.dir/osl.cpp.o
>/media/teddd/IHD/tmp/bpy/build/temp.linux-x86_64-3.7/blender/intern/cycles/render/../kernel/osl/osl_services.h:176:33: error: ‘OpenImageIO_v2_1::TextureSystem::TextureHandle* ccl::OSLRenderServices::get_texture_handle(OpenImageIO_v2_1::ustring)’ marked ‘override’, but does not override
>TextureSystem::TextureHandle *get_texture_handle(ustring filename) override;
>/media/teddd/IHD/tmp/bpy/build/temp.linux-x86_64-3.7/blender/intern/cycles/render/../kernel/osl/osl_services.h:227:8: error: ‘bool ccl::OSLRenderServices::get_texture_info(OSL_v1_11::ShaderGlobals*, OpenImageIO_v2_1::ustring, OSL_v1_11::RendererServices::TextureHandle*, int, OpenImageIO_v2_1::ustring, OpenImageIO_v2_1::TypeDesc, void*)’ marked ‘override’, but does not override
>bool get_texture_info(OSL::ShaderGlobals *sg,
>make[2]: *** [intern/cycles/render/CMakeFiles/cycles_render.dir/build.make:336: intern/cycles/render/CMakeFiles/cycles_render.dir/osl.cpp.o] Error 1
>make[2]: Leaving directory '/media/teddd/IHD/tmp/bpy/build/temp.linux-x86_64-3.7/build'

Any idea where that could come from ? I installed the libs using the shell script `install_deps.sh` like recommended the the Blender developer documentation.

Running `uname -a` returns

> Linux debianteddd 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

**Comment by TylerGubala** [comment]
Hi,

I think that you should probably follow the [Installation instructions](https://github.com/TylerGubala/blenderpy#installing) and use the one on PYPI.

I did not have a `wheel` up there for a bit because of upload size limitations. I apologize for any inconvenience. 

Try following the [installation instructions](https://github.com/TylerGubala/blenderpy#installing) again and let me know if you need help afterwards.

Thank you for your patience.

**Comment by theottm** [comment]
Hello,

this is basically what I did, I think. The Installation instruction says to run `pip install bpy && bpy_post_install` which is equivalent to running `pip install bpy` and latter on `bpy_post_install`. What I ran was `pip install bpy ` with additional option `-b /media/teddd/IHD/tmp/` which should just locate the temporary directory for the build to my other hard drive, because I don't have enough space on my `/tmp`. I don't think this can be the reason for the bug. Or am I overlooking something here ?

**Comment by theottm** [comment]
I just used an environment variable to set the build directory. So I ran exactly what is in installation guide, that is without the -b option. I still get the exact same error.

**Comment by TylerGubala** [comment]
Try

pip install bpy==2.91a0 && bpy_post_install

**Comment by theottm** [comment]
Yeah, it worked !
Thanks for your help :)

**Comment by TylerGubala** [comment]
Great, let me know if you need anything else.

**Comment by theottm** [comment]
Hi!
i wanted to install it again but the version you suggested (2.91a0) is not available when running `pip install bpy==2.91a0 && bpy_post_install`

**Comment by theottm** [comment]
Also tried `pip install bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl && bpy_post_install` after downloading the corresponding wheel.
But I get `bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl is not a supported wheel on this platform.` 
I'm on Debian Buster with python 3.7.0

**Comment by TylerGubala** [comment]
Are you on 64-bit?

**Comment by theottm** [comment]
Yes.
(sorry, I didn't get notified)
