### ISSUE TITLE
rendering to view node question

### ISSUE THREAD

**Issue by jdily** [TylerGubala/blenderpy#79]
**Describe the bug**
I use the bpy module remotely to render some scenes (I currently using WORKBENCH renderer).
The rendering is success if I export the rendering result directly.
That is, I set `bpy.ops.render.render(animation=False, write_still=True)`
However, if i want to access the rendered result using the viewer node i set, I got the wrong size and no content.
I have tested using Blender to run the same code on my laptop and the behavior is correct.
But not on remote machine with bpy module.

**To Reproduce**

```
def render_cur_scene(layer_name="ori_layer", obs_size=(16,16), ind=0):
    scene = bpy.context.scene
    scene.render.engine = 'BLENDER_WORKBENCH'
    scene.render.resolution_x = obs_size[0]
    scene.render.resolution_y = obs_size[1]
    for scene in bpy.data.scenes:
        scene.render.engine = 'BLENDER_WORKBENCH'
        scene.render.resolution_x = obs_size[0]
        scene.render.resolution_y = obs_size[1]
    bpy.context.scene.display.shading.color_type = 'TEXTURE'
    bpy.context.scene.display.shading.light = 'FLAT'
    bpy.context.scene.world.color = (0, 0, 0)
    bpy.context.scene.view_settings.view_transform = 'Standard'
    scene.view_layers[layer_name].use_pass_z = True

    tree = bpy.context.scene.node_tree
    print('how many tree nodes : ', len(tree.nodes))
    rl = tree.nodes.new('CompositorNodeRLayers')      
    rl.location = 185,285
    rl.layer = layer_name
    v = tree.nodes.new('CompositorNodeViewer')   
    v.location = 750,210
    v.use_alpha = False

    tree.links.new(rl.outputs['Image'], v.inputs['Image'])  # link Image output to Viewer input
    scene.render.filepath = "./test_render_%d.png"%(ind)
    bpy.ops.render.render(animation=False, write_still=False)
    b_img = bpy.data.images['Viewer Node']
    width, height = b_img.size
    img = np.copy(np.array(b_img.pixels).reshape(height, width, -1))
    img = np.flipud(img)
    imageio.imwrite("./saved_render.png", img*255)
```

**Expected behavior**
I expect that the width and height should be 16 (the resolution_x and resolution_y I set).
But they are both 256, and the img I got is totally blank.
However, if I set write_still = True, I can get the correct render result in test_rendeR_%d.png.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

Thank you so much, and please let me know if I should add more details.

**Comment by jdily** [comment]
I just found out this is probably relevant:
https://blender.stackexchange.com/questions/195289/compositor-viewer-node-output-never-updates-when-rendering-via-python-script

**Comment by TylerGubala** [comment]
This functionality is just plain broke in `bpy` as shipped by BF. You cannot do it.

But! If you want to clone this repo I suggest the following:

1. Get Visual Studio Code
2. Open this Repo with VS Code
3. Run the "First Time - Git and SVN Checkout"
4. Make the modifications in the linked Blender SE site (note, I have not tried their suggestion) in the `Blender/blender` git submodule
5. run the VS Code Task "Build"
6. Let me know your results!

If you want a feature added to Blender, you can always try [Blender Developer Talk](https://devtalk.blender.org/)
