### ISSUE TITLE
bpy_post_install fails: Could not find Blender scripts directory

### ISSUE THREAD

**Issue by basilevh** [TylerGubala/blenderpy#83]
**Describe the bug**
I'm trying to install blenderpy inside an Anaconda environment on Ubuntu 18.04 (with Blender itself not already installed).
bpy_post_install has no console output at first, but eventually fails in finding the Blender scripts directory.

**To Reproduce**
1. Run `pip install bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64`.
2. Run `bpy_post_install`.
3. Wait for a long time, and then get: `blenderpy.BlenderScriptsDirUnknownError: Could not find Blender scripts directory in /home/username`.

**Expected behavior**
Perhaps bpy_post_install should provide a way of letting us point to the scripts directory, with a description of what exactly it's searching for?

**Machine:**
 - OS: Ubuntu 18.04.5 LTS
 - Version: bpy 2.91a0

**Additional context**
My conda environment location is `/home/username/miniconda3/bin/python3`, though the miniconda3 folder is actually a symlink to somewhere else (if that is relevant).

Any idea how to resolve this? Thanks in advance!

**Comment by basilevh** [comment]
Actually, as I suspected, the symbolic link for my base environment (from my user folder to another disk) was the culprit. I managed to resolve the issue by creating a new environment directly on that other disk with the intent of doing my Blender work in there.

For future visitors, try to check if there are no directory junctions / symbolic links possibly interfering with the post_install.py script trying to find the Blender scripts directory.

I guess my bug report is therefore that the calls to `os.walk()` don't take symlinks into account -- I'll let the author of this repository decide whether to close this issue now that we found a solution, or to update the package to address this particular edge case first.

**Comment by TylerGubala** [comment]
Sorry I haven't had time to check if I can reproduce your issue but I don't see the harm in adding `follow_links= True` to the call to `os.walk` so I put it in. Maybe that will help you.

For what it's worth though, before I read through the whole issue I set up a windows environment and performed a short test and couldn't reproduce it, but that's neither here nor there.

Happy coding!
