### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by stefnotch** [TylerGubala/blenderpy#9]
I have Visual Studio 2017 with C++ build tools installed. I also installed cmake using `py -m pip install cmake`. However, when I attempt to install `bpy`, the following error pops up:

```
C:\WINDOWS\system32>py -m pip install bpy
Collecting bpy
  Using cached https://files.pythonhosted.org/packages/5d/03/9896a05aac246d3a46b1a49c1eb796a51ecc4e0ae30e9e7c5d52cbc52662/bpy-1.2.1.tar.gz
Installing collected packages: bpy
  Running setup.py install for bpy ... error
    Complete output from command "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\STEFNO~1\\AppData\\Local\\Temp\\pip-install-hxt_u2p9\\bpy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\STEFNO~1\AppData\Local\Temp\pip-record-4mrnmz5l\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Preparing the build environment
    Cloning Blender source from git://git.blender.org/blender.git...
    Updating Blender git submodules...
    Checking out svn libs from https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc14...
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command ""C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\STEFNO~1\\AppData\\Local\\Temp\\pip-install-hxt_u2p9\\bpy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\STEFNO~1\AppData\Local\Temp\pip-record-4mrnmz5l\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\STEFNO~1\AppData\Local\Temp\pip-install-hxt_u2p9\bpy\
```

Maybe relevant:
- I ran it in an administrator cmd window
- The directory `C:\Users\STEFNO~1\AppData\Local\Temp\pip-install-hxt_u2p9\bpy\` doesn't seem to exist.
- I temporarily added cmake to my path `SET PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts`

**Comment by TylerGubala** [comment]
Sorry, this is because I didn't have a great set of requirements written down.

I wrote this module only after carefully building blender from sources by hand; the result was I ended up forgetting to list a lot of the requirements for the module to work.

The WinError that you are receiving there, I am almost 99% certain is the result of Windows not being able to find the executable for svn. Do you have an svn provider installed? I recommend Tortoise SVN, and install "With Command line client tools" per this stackoverflow question, which will add the command "svn" to your system path.

https://stackoverflow.com/questions/1625406/using-tortoisesvn-via-the-command-line

After performing this installation, try again and get back with me if you please. If that resolves the issue (which I believe it should) you will get a fully built installation of bpy.pyd in your environment's path.

Also related: https://blenderartists.org/t/pip-installable-bpy-module/1116741/6

**Comment by stefnotch** [comment]
No, I don't have an svn provider installed. However, `git`, which is far more wide spread than `svn` these days, [can apparently be used for svn stuff.](https://git-scm.com/book/en/v1/Git-and-Other-Systems-Git-and-Subversion).

**Comment by TylerGubala** [comment]
I rely on SVN Python for building from sources, as part of the requirement for building Blender from sources is SVN as shown on the "Building Blender" wikia page:

https://wiki.blender.org/wiki/Building_Blender/Windows#Download_Sources_and_Libraries_2

I tend to prefer this method as its the official reccomendation from the Blender Foundation, however it is quite interesting to know that you can use git as a standin for svn, so thanks for letting me know about that! 

The requirement to install any of these dependencies should go away once I am able to provide an accurate bdist_wheel, which is hopefully soon, but I have to figure out a few tricks on the setup scripts end first, namely getting it to track all the files in egg-info.

**Comment by TylerGubala** [comment]
I am able to generate a bdist_wheel that appears to have everything.

Currently I need privilages to upload file sizes greater than 60MB to pypi to have this workable for you (my bdist_wheel is ~66MB)

https://github.com/pypa/packaging-problems/issues/185

I don't want to jump the gun but I am hoping that this resolves multiple issues, including this one. By having a bdist_wheel, you won't require all of the build software dependencies.

**Comment by TylerGubala** [comment]
I uploaded a bdist_wheel for version 1.2.2

Hopefully this resolves your issue, provided you are on Python 3.6 Win64.

Please try and get back to me if there is any issue. I am closing this issue as I am able to get 

`import bpy`

functionality in my venv without cmake, or the binary build dependencies.

**Comment by stefnotch** [comment]
Tested it, seems to work perfectly now.

**Comment by hugoliv** [comment]
Facing the same problem on OSX. Maybe a wheel for OSX should help ? 🙏

**Comment by TylerGubala** [comment]
There's a wheel available for OSX on the releases page.

https://github.com/TylerGubala/blenderpy/releases

**Comment by hugoliv** [comment]
Thank you. But no way to make it work with `pipenv` :

Pipfile:

```[packages]
numpy = "*"
requests = "*"
future-fstrings = "*"
bpy = {path = "./bpy-2.91a0-cp37-cp37m-macosx_10_13_x86_64.whl"}

[dev-packages]

[requires]
python_version = "3.7"
```


Output when the "import bpy" is reached:

```Color management: using fallback mode for management
Color management: Error could not find role data role.
BLT_lang_init: 'locale' data path for translations not found, continuing
Color management: scene view "Filmic" not found, setting default "Standard".
blf_load_font_default: 'fonts' data path not found for 'droidsans.ttf', will not be able to display text
blf_load_font_default: 'fonts' data path not found for 'bmonofont-i18n.ttf', will not be able to display text
blf_load_font_default: 'fonts' data path not found for 'bmonofont-i18n.ttf', will not be able to display text
bpy: couldn't find 'scripts/modules', blender probably wont start.
Freestyle: couldn't find 'scripts/freestyle/modules', Freestyle won't work properly.
ModuleNotFoundError: No module named 'bpy_types'
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Users/tylergubala/Code/Python/blenderpy/Blender/blender/source/blender/python/intern/bpy_rna.c:7241 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Users/tylergubala/Code/Python/blenderpy/Blender/blender/source/blender/python/intern/bpy_rna.c:7241 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Users/tylergubala/Code/Python/blenderpy/Blender/blender/source/blender/python/intern/bpy_rna.c:7241 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Users/tylergubala/Code/Python/blenderpy/Blender/blender/source/blender/python/intern/bpy_rna.c:7241 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Users/tylergubala/Code/Python/blenderpy/Blender/blender/source/blender/python/intern/bpy_rna.c:7241 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Users/tylergubala/Code/Python/blenderpy/Blender/blender/source/blender/python/intern/bpy_rna.c:7241 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Users/tylergubala/Code/Python/blenderpy/Blender/blender/source/blender/python/intern/bpy_rna.c:7241 pyrna_srna_ExternalType: failed to find 'bpy_types' module
F0514 10:00:02.448935 304098816 utilities.cc:346] Check failed: !IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!
*** Check failure stack trace: ***
    @        0x114c0f91f  google::LogMessageFatal::~LogMessageFatal()
    @        0x114c0bbe9  google::LogMessageFatal::~LogMessageFatal()
    @        0x114c1497c  google::glog_internal_namespace_::InitGoogleLoggingUtilities()
    @        0x11321640e  libmv_initLogging
    @        0x112383be2  main_python_enter
    @        0x112cd3b87  dealloc_obj_dealloc
    @        0x105c5279c  insertdict
    @        0x105c56396  PyDict_SetItemString
    @        0x105d0f1a0  PyModule_AddObject
    @        0x105d0aa93  _PyImport_LoadDynamicModuleWithSpec
    @        0x105d0a209  _imp_create_dynamic
    @        0x105c2a556  _PyMethodDef_RawFastCallDict
    @        0x105c2a231  PyCFunction_Call
    @        0x105ce746f  _PyEval_EvalFrameDefault
    @        0x105ceab63  _PyEval_EvalCodeWithName
    @        0x105c29f31  _PyFunction_FastCallKeywords
    @        0x105cea012  call_function
    @        0x105ce6fdd  _PyEval_EvalFrameDefault
    @        0x105c2a3a0  function_code_fastcall
    @        0x105cea012  call_function
    @        0x105ce6fc3  _PyEval_EvalFrameDefault
    @        0x105c2a3a0  function_code_fastcall
    @        0x105cea012  call_function
    @        0x105ce707e  _PyEval_EvalFrameDefault
    @        0x105c2a3a0  function_code_fastcall
    @        0x105cea012  call_function
    @        0x105ce707e  _PyEval_EvalFrameDefault
    @        0x105c2a3a0  function_code_fastcall
    @        0x105cea012  call_function
    @        0x105ce707e  _PyEval_EvalFrameDefault
    @        0x105c2a3a0  function_code_fastcall
    @        0x105c29994  _PyFunction_FastCallDict```

**Comment by TylerGubala** [comment]
You would have to run "bpy_post_install" after installation to get it to
work.
